version: "3.8"

services:
  notion-webhook:
    build: .
    container_name: notion-webhook
    ports:
      - "4325:4325"
    environment:
      - PORT=4325
    networks:
      - plugin_default
    restart: always

networks:
  plugin_default:
    external: true

